# Generated by Django 6.0.1 on 2026-02-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seatingallotment',
            unique_together={('exam', 'hall', 'seat_number')},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examhall',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seatingallotment',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')]),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'exam_date', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='seatingallotment',
            unique_together={('exam', 'hall', 'seat_number'), ('student', 'exam')},
        ),
    ]
