# Generated by Django 6.0.1 on 2026-02-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_building_alter_seatingallotment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhall',
            name='Building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allotment.building'),
            preserve_default=False,
        ),
    ]
