# Generated by Django 6.0.1 on 2026-02-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0004_examhall_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examhall',
            old_name='Building',
            new_name='building',
        ),
    ]
