# Generated by Django 6.0.1 on 2026-02-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0005_rename_building_examhall_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['exam_date', 'session']},
        ),
        migrations.AlterModelOptions(
            name='examhall',
            options={'ordering': ['hall_no']},
        ),
        migrations.AlterModelOptions(
            name='seatingallotment',
            options={'ordering': ['exam', 'hall', 'seat_number']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['reg_no']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code']},
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='allotment.subject'),
        ),
        migrations.AlterField(
            model_name='examhall',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='allotment.building'),
        ),
        migrations.AlterField(
            model_name='seatingallotment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='allotment.exam'),
        ),
        migrations.AlterField(
            model_name='seatingallotment',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='allotment.examhall'),
        ),
        migrations.AlterField(
            model_name='seatingallotment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='allotment.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='allotment.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='allotment.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='allotment.department'),
        ),
    ]
